// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdLPvMzA18XLZZthI_KA_3OhzPtotbFe8',
    appId: '1:1039530380530:web:078ba7eb82cb664f74d46b',
    messagingSenderId: '1039530380530',
    projectId: 'proyectoflutter7',
    authDomain: 'proyectoflutter7.firebaseapp.com',
    storageBucket: 'proyectoflutter7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpYmoENEDfQcqh7P61-hUcXO1PLcF_hs',
    appId: '1:1039530380530:android:9e77fb8c24fd99a474d46b',
    messagingSenderId: '1039530380530',
    projectId: 'proyectoflutter7',
    storageBucket: 'proyectoflutter7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdLPvMzA18XLZZthI_KA_3OhzPtotbFe8',
    appId: '1:1039530380530:web:c54b9412515b9ace74d46b',
    messagingSenderId: '1039530380530',
    projectId: 'proyectoflutter7',
    authDomain: 'proyectoflutter7.firebaseapp.com',
    storageBucket: 'proyectoflutter7.firebasestorage.app',
  );

}